parameters:
    jc_queue.manager.class: JC\QueueBundle\Manager\Manager

services:
    jc_queue.manager:
        class: %jc_queue.manager.class%
        #arguments: [@service_id, "plain_value", %parameter%]